if (NOT DEFINED ARA_USE_FFMPEG)
    set(ARA_USE_FFMPEG ON)
endif()
if (NOT DEFINED ARA_USE_OPENAL)
    set(ARA_USE_OPENAL ON)
endif()
if (NOT DEFINED ARA_USE_PORTAUDIO)
    set(ARA_USE_PORTAUDIO ON)
endif()
if (NOT DEFINED ARA_USE_NDI)
    set(ARA_USE_NDI ON)
endif()
if (NOT DEFINED ARA_USE_ARCORE)
    set(ARA_USE_FREEIMAGE OFF)
endif()
if (NOT DEFINED ARA_USE_REALSENSE)
    set(ARA_USE_REALSENSE OFF)
endif ()

if (ANDROID)
    if (NOT DEFINED ARA_USE_ARCORE)
        set(ARA_USE_ARCORE ON)
    endif ()
    set(ARA_USE_MEDIACODEC ON)
    set(ARA_USE_REALSENSE OFF)
endif()


# translate cmake switches to preprocessor flags - nothing to do configure manually here
if (ARA_USE_REALSENSE)
    add_compile_definitions(ARA_USE_REALSENSE)
endif()
if (ARA_USE_FFMPEG)
    add_compile_definitions(ARA_USE_FFMPEG)
endif()
if (ARA_USE_OPENAL)
    add_compile_definitions(ARA_USE_OPENAL)
endif()
if (ANDROID AND ARA_USE_ARCORE)
    add_compile_definitions(ARA_USE_ARCORE)
endif()
if (ARA_USE_PORTAUDIO)
    add_compile_definitions(ARA_USE_PORTAUDIO)
endif()
if (ARA_USE_NDI)
    add_compile_definitions(ARA_USE_NDI)
endif()